### ISSUE TITLE
quotes around table name

### ISSUE THREAD

**Issue by michel-reyes** [sdesalas/websqldump#1]
Hello, excellent plugin...
I have a table called transaction, in my project a i have some problems, but i fixed
now in the websqldump i found the same issue and i fixed too

line 57:  sql: "SELECT \* FROM '" + table + "';", // addquotes around the table name

**Comment by sdesalas** [comment]
Hi Neomicho!

You are awesome!! Always happy to find out other people are using/testing my code too.. Thanks for the fix, applying right away!!

Steven
