### ISSUE TITLE
Don't Understand How to Send DB to Remote Server 

### ISSUE THREAD

**Issue by 4k-developer** [sdesalas/websqldump#4]
The example server says http://myserver.com/sync but don't understand when making my own server how do I make it so I can upload to it? Do you get what I mean?

**Comment by sdesalas** [comment]
You'll need to write a web app or a web API that integrates with your database for this. You'll also need to implement some sort of authentication to make sure your sync entry point does not get hacked. 

This is well beyond the scope of this project and depends a lot on which programming language you are familiar with. You could use C#, Nodejs, PHP, Java, Ruby.. And the list goes on and on. 

If you are unfamiliar with this stuff I recommend you hire a coder. Try search for 'hire a coder' on google for some suggestions.

**Comment by 4k-developer** [comment]
WebSQL/JS

**Comment by sdesalas** [comment]
Maybe NodeJS will be a good option as its server-side JavaScript. You should be able to get a basic free solution running on heroku.

**Comment by sdesalas** [comment]
https://devcenter.heroku.com/articles/getting-started-with-nodejs

https://codeforgeek.com/2015/01/nodejs-mysql-tutorial/

**Comment by 4k-developer** [comment]
Okay thanks for your help! I'm a bit busy i'll check it out later and let you know how it goes.

**Comment by sdesalas** [comment]
No worries, good luck there.

**Comment by nueko** [comment]
DropBox or Google Drive feature would be great :+1:

**Comment by sdesalas** [comment]
LOL 👍 

How about a cup holder too?
